from mcp.server.fastmcp import FastMCP
import pandas as pd
import os

# Initialize FastMCP server
mcp = FastMCP("FinanceAnalysisServer")

# Global variable to hold data for the session
DATA_PATH = "transaction_data.csv"

@mcp.tool()
def get_data_schema() -> str:
    """Returns the column names and data types of the loaded financial data."""
    if not os.path.exists(DATA_PATH):
        return "Error: No data file found. Please upload a file first."
    df = pd.read_csv(DATA_PATH)
    return str(df.dtypes.to_dict())

@mcp.tool()
def run_pandas_logic(python_code: str) -> str:
    """Executes pandas code on the 'df' variable and returns the 'final_result'."""
    if not os.path.exists(DATA_PATH):
        return "Error: Data file missing."
    
    df = pd.read_csv(DATA_PATH)
    local_vars = {'df': df}
    try:
        # Executes the code generated by the LLM
        exec(python_code, {}, local_vars)
        return str(local_vars.get('final_result', "No result found."))
    except Exception as e:
        return f"Python Error: {str(e)}"

if __name__ == "__main__":
    mcp.run(transport="stdio")